import SideBar from "@/app/components/Sidebar/sidebar";
import { ThemeSwitcher } from "@/app/components/ThemeSwitcher";
import Nav from "@/app/components/nav/nav";
import NavDashboard from "@/app/components/nav/nav-dashboard";
import CourseSideBar from "@/app/components/protected/sidebar/course-sidebar";
import UserCard from "@/app/components/user-card";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });
import translations from "@/langs.json";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CourseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const lang = cookieStore.get("lang");
  let langague = null;

  if (lang?.value === "gb") {
    langague = translations.gb;
  } else if (lang?.value === "me") {
    langague = translations.me;
  } else if (lang?.value === "sq") {
    langague = translations.al;
  } else {
    langague = translations.gb;

  }
  return (
    <div>
      <Nav lang={langague}></Nav>

      <div className="flex justify-center">
        <div className="relative flex place-items-center before:absolute before:h-[700px] before:w-full sm:before:w-[280px] left-1/2 bottom-96 before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-full sm:after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]"></div>
        <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-full sm:before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-full sm:after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-green-200 after:via-green-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-green-700 before:dark:opacity-10 after:dark:from-green-900 after:dark:via-green-500 after:dark:opacity-40 before:lg:h-[360px] z-[-1]"></div>

        {children}
      </div>
    </div>
  );
}
